### ISSUE TITLE
Any new issues?

### ISSUE THREAD

**Issue by KenzoM** [eggheadio-github/stack-overflow-copy-paste#66]
Hello 
Sorry if I am asking a very noob question but I don't see any new issues that new comers can tackle on. Normally, do we ask for issues to work, or do we simply address to the project manager and then ask for permission to work on?

I am very new to open source community so I am not where to begin.

**Comment by kentcdodds** [comment]
Hi @KenzoM!
Thanks for the issue! Normally, if there's a project you want to contribute to, there will be existing issues which you can look at and if you feel like you can tackle them, you comment to say that you're interested in contributing and would like to tackle the issue. You're free to go ahead and get started whenever you like, but it's often good to wait until you hear back from a maintainer because they may have some useful information or let you know that someone's already working on it.

For this particular project, the whole point is for you to learn how to contribute to open source. So feel free to search StackOverflow for a generic function you can add to the project and file an issue asking whether you can add it and I'll get back to you as soon as I'm able.

Good luck!

**Comment by kentcdodds** [comment]
Also, welcome to the world of Open Source!

**Comment by KenzoM** [comment]
@kentcdodds Thanks brotha! I am excited to find something that I can help around with!
